[workspace]
resolver = "2"
members = [
    "stream-core",
    "stream-hooks",
]

[workspace.package]
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/riverpay/riverpay"

[profile.release]
opt-level = "z"
overflow-checks = true
debug = 0
strip = "symbols"
debug-assertions = false
panic = "abort"
codegen-units = 1
lto = true
